## TIME SERIES FORECAST

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
airline_dataset = pd.read_csv('dataset/airline-passengers.csv')

In [3]:
airline_dataset.head()

Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121

In [4]:
airline_dataset.isnull().sum().sum()

0

In [5]:
# there are no null values

In [6]:
# there is no categorical value
# there is no question of imblance dataset because its kind of regression task
# don't know about outliers, need to check

In [7]:
import torch

In [8]:
from torch import nn

In [9]:
from torch.utils.data import DataLoader, Dataset

In [10]:
class DLoader(DataLoader):
    def __init__(self):
        super(Dloader, self).__init__()
    
    def __getitem__(ind):
        return airline_dataset.iloc[ind]['Month'], airline_dataset.iloc[ind]['Passengers']
    def __len__():
        return len(airline_dataset)
        

In [11]:
type(airline_dataset.iloc[2]['Passengers'])

numpy.int64

In [12]:
airline_dataset = airline_dataset['Passengers']
airline_dataset.head()

0    112
1    118
2    132
3    129
4    121
Name: Passengers, dtype: int64

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler = MinMaxScaler(feature_range=(0, 1))

In [15]:
airline_dataset = airline_dataset.astype('float32')
airline_dataset

0      112.0
1      118.0
2      132.0
3      129.0
4      121.0
       ...  
139    606.0
140    508.0
141    461.0
142    390.0
143    432.0
Name: Passengers, Length: 144, dtype: float32

In [16]:
import numpy as np
dataset = [x for x in airline_dataset]
dataset = np.reshape(dataset, (-1, 1))
dataset[:5]

array([[112.],
       [118.],
       [132.],
       [129.],
       [121.]])

### see how the code below works ie. datatype.astype()

In [17]:
# dataframe = pd.read_csv('dataset/airline-passengers.csv', usecols=[1], engine='python')
# dataset = dataframe.values
# dataset = dataset.astype('float32')
# # normalize the dataset


In [18]:
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

In [19]:
dataset[:5]

array([[0.01544402],
       [0.02702703],
       [0.05405405],
       [0.04826255],
       [0.03281853]])

In [20]:
def create_dataset(dataset, lookback=2):
    dataX, dataY= [], []
    for i in range(len(dataset)-lookback-1):
        xval = dataset[i:i+lookback, 0]
        yval = dataset[i+lookback, 0]
        dataX.append(xval)
        dataY.append(yval)
    return dataX, dataY

In [21]:
# splitting into training and testing
# lets take 67 percent for training

In [22]:
dataX, dataY = create_dataset(dataset, lookback=2)

In [23]:
dataX[:5]
print(len(dataX))

141


In [24]:
dataY[:5]

[0.05405405405405403,
 0.04826254826254825,
 0.03281853281853281,
 0.05984555984555981,
 0.08494208494208491]

In [25]:
dataset[:5]

array([[0.01544402],
       [0.02702703],
       [0.05405405],
       [0.04826255],
       [0.03281853]])

In [26]:
# LSTM input dimension is (batch_size, seq_lenght, input_size)

In [27]:
# here we have a seq_len of 2, the input size is 1

In [28]:
class Model(nn.Module):
    def __init__(self,input_size, hidden_size, num_layers):
        super(Model, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.input_size = input_size
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first= True) # batch first tells the first dimension is batch

    def forward(self, x):
        out = self.lstm(x)
        return out

In [29]:
train_size = int(len(dataset)*0.67)
test_size = len(dataset)-train_size

In [49]:
train_x = dataX[:train_size]
test_x = dataX[train_size:]

train_y = dataY[:train_size]
test_y = dataY[train_size:]



class AirlineData(Dataset):
    def __init__(self, st):
        print('the length is : ', len(train_x), len(test_x))
        torch.tensor(train_x[2],dtype = torch.float32)
        self.st = st
        
    def __getitem__(self, index):
        if(self.st == 'train'):
            return torch.tensor(train_x[index],dtype = torch.float32), torch.tensor(train_y[index], dtype=tensor.float32)
        elif(self.st == 'test'):
            return torch.tensor(test_x[index],dtype = torch.float32), torch.tensor(test_y[index], dtype=tensor.float32)
    def __len__(self):
        if self.st == 'train':
            return len(test_x)
        else:
            return len(train_x)

In [50]:
train_x = AirlineData('train')
dataloader = DataLoader(train_x, shuffle = False, batch_size=1)

the length is :  96 45


In [51]:
from tqdm import tqdm

In [ ]:
from sklearn.metrics import mean_squared_error as mse

for epoch in range(4):
    print("epoch : ", epoch)
    for batch_ind, dataxy in enumerate(tqdm(dataloader)):
        print('hello')
           
        
        
        
            

  0%|                                                                                           | 0/45 [00:00<?, ?it/s]

In [ ]:
input_size, hidden_size, num_layers = 2, 128, 2
model = Model(input_size, hidden_size, num_layers)